=== JGCRI/pygcam/pygcam/etc/mcsValues-schema.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:include schemaLocation="comment.xsd"/>
    
    <xs:element name="scenario">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="world" maxOccurs="1"/>
                <xs:element ref="comment" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="world">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="region" maxOccurs="unbounded"/>
                <xs:element ref="comment" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="region">
        <xs:complexType>
            <xs:choice>
                <xs:element ref="values"/>
                <xs:element ref="comment" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="values">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="value"/>
                <xs:element ref="comment"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="value">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="name" use="required"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== JGCRI/pygcam/tests/data/xml/mcsValues-example.xml
<?xml version="1.0" encoding="UTF-8"?>
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../../pygcam/etc/mcsValues-schema.xsd">
	<world>
		<region name="USA">
			<values>
				<value name="corn ethanol">0.5</value>
				<value name="cellulose ethanol">0.25</value>
				<value name="biodiesel">0.25</value>
			</values>
		</region>
		<region name="China">
			<values>
				<value name="corn ethanol">1.5</value>
				<value name="cellulosic ethanol">1.25</value>
				<value name="biodiesel">0.25</value>
			</values>
		</region>
	</world>
</scenario>
