=== JGCRI/pygcam/pygcam/etc/project-schema.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- Derived using MOSO Xmplify 1.7.6 by Richard Plevin on 2016-01-30 17:59:46 +0000 -->
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
    <xs:element name='projects'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='defaults'/>
                <xs:element ref='project'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='defaults'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='steps'/>
                <xs:element ref='tmpFile'/>
                <xs:element ref='vars'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name='project'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='steps'/>
                <xs:element ref='tmpFile'/>
                <xs:element ref='vars'/>
                <xs:element ref='scenario'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='scenario'>
        <xs:complexType>
            <xs:attribute name='active' type='xs:integer'/>
            <xs:attribute name='baseline' type='xs:integer'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
            <xs:attribute name='subdir' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='vars'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='var'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='var'>
        <xs:complexType mixed='true'>
            <xs:attribute name='configVar' type='xs:NCName'/>
            <xs:attribute name='eval' type='xs:integer'/>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='tmpFile'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='text'/>
            </xs:sequence>
            <xs:attribute name='delete' type='xs:integer'/>
            <xs:attribute name='eval' type='xs:integer'/>
            <xs:attribute name='replace' type='xs:integer'/>
            <xs:attribute name='varName' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='text'>
        <xs:complexType mixed='true'>
            <xs:attribute name='tag' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='steps'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='step'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='step'>
        <xs:complexType mixed='true'>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
            <xs:attribute name='runFor' type='xs:NCName'/>
            <xs:attribute name='seq' use='required' type='xs:integer'/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== JGCRI/pygcam/pygcam/etc/examples/project.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file defines the "tutorial" project. Feel free to edit it to your liking.
Also see project2.xml, which offers a slightly more complex example.
-->
<projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="project-schema.xsd">
  <project name="ctax">
    <vars>
      <var name="startYear">2015</var>
      <var name="endYear">2050</var>  <!-- stops at 2050 so tutorial runs faster -->
      <var name="years" eval="1">{startYear}-{endYear}</var>
    </vars>
    <steps>
      <!--
      The names defined in steps can be used on the command-line to limit operations to
      these steps. Steps are run in the order defined in this file, regardless of the
      order specified to "gt run". If runFor="baseline", the step is run only for baseline
      scenarios. If runFor="policy", the step is run only for non-baseline scenarios. If
      not set (or set to any other value) the step is run for all scenarios.
       -->
      <step name="setup" runFor="baseline">
        @setup -b "{baseline}" -g "{scenarioGroup}" -S "{scenarioSubdir}" -w "{scenarioDir}"
               -p {endYear} -y {years}
      </step>
      <step name="gcam"  runFor="baseline">@gcam -s "{baseline}" -S "{projectXmlDir}"</step>
      <step name="query" runFor="baseline">
        @query -o "{batchDir}" -w "{scenarioDir}" -s "{scenario}" -q "{queryXmlFile}"
      </step>

      <!--
        Explicitly require policy setup, gcam, and query steps to run after baseline to
        allow baseline results to be used in constraints
      -->
      <step name="setup" runFor="policy">
            @setup -b "{baseline}" -s "{scenario}" -g {scenarioGroup} -S "{scenarioSubdir}"
                   -w "{scenarioDir}" -p {endYear} -y {years}
      </step>
      <step name="gcam"  runFor="policy">@gcam -s "{scenario}" -S "{projectXmlDir}"</step>
      <step name="query" runFor="policy">
        @query -o {batchDir} -w "{scenarioDir}" -s "{scenario}" -q "{queryXmlFile}"
      </step>

      <!--
        Compute and plot differences between query results for policy and baseline scenarios
      -->
      <step name="diff"  runFor="policy">
        @diff -D "{sandboxDir}" -y {years} -q "{queryXmlFile}" "{baseline}" "{scenario}"
      </step>
      <step name="plotDiff" runFor="policy">
        @chart {diffPlotArgs} --reference "{baseline}" --scenario "{scenario}" --fromFile "{diffPlots}"
      </step>

      <!-- Generate an XLSX workbook from all CSV query result files -->
      <step name="xlsx"  runFor="policy">
        @diff -D "{diffsDir}" -c -y {years} -o diffs.xlsx {diffsDir}/*.csv
      </step>
    </steps>

    <!--
      Define which queries to run. This creates a text file whose name is stored
      in a project variable, accessed as {queryXmlFile} in the "query" step.
    -->
    <queries varName="queryXmlFile">
      <query name="LUC_emissions_by_region"/>
      <query name="total_climate_forcing"/>
      <query name="global_mean_temperature"/>
    </queries>

    <vars>
      <!-- common arguments for 'diffPlots' -->
      <var name="diffPlotArgs" eval="1">-D "{diffsDir}" --outputDir figures --years {years} --label --ygrid --zeroLine</var>
    </vars>

    <tmpFile varName="diffPlots">
      <text>LUC_emissions_by_region-{scenario}-{reference}.csv -Y 'Tg CO$_2$' -m C_to_CO2 -i -n 4 -T '$\Delta$ LUC emissions' -I region -x by-region.png</text>

      <!-- Forcing and temperature change -->
      <text>total_climate_forcing-{scenario}-{reference}.csv   -Y 'W/m$^2$' --timeseries -T '$\Delta$ Total Climate Forcing'</text>
      <text>global_mean_temperature-{scenario}-{reference}.csv -Y 'Degrees C' --timeseries -T '$\Delta$ Global Mean Temperature'</text>
    </tmpFile>

  </project>
</projects>

=== JGCRI/pygcam/pygcam/etc/examples/project2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
This file defines one or more "projects" that are run using the "gt run" subcommand.
-->
<projects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="project-schema.xsd">
	<project name="ctax">
		<vars>
			<var name="startYear">2015</var>
			<var name="endYear">2050</var>  <!-- stops at 2050 so tutorial runs faster -->
			<var name="years" eval="1">{startYear}-{endYear}</var>
		</vars>
		<steps>
			<!--
			The names defined in steps can be used on the command-line to limit operations to these steps.
			If runFor="baseline", the step is run only for baseline scenarios. If runFor="policy", the step
			is run only for non-baseline scenarios. If not set (or set to any other value) the step is run
			for all scenarios.
			 -->
			<step name="setup" runFor="baseline">@setup -b {baseline} -g {scenarioGroup} -S {scenarioSubdir} -w {scenarioDir} -p {endYear} -y {years}</step>
			<step name="prequery" runFor="baseline">@query -p -o {batchDir} -w {scenarioDir} -s {scenario} -q "{queryXmlFile}"</step>
			<step name="gcam"  runFor="baseline">@gcam -s {baseline} -S {projectXmlDir} </step>
			<step name="query" runFor="baseline">@query -o {batchDir} -w {scenarioDir} -s {scenario} -q "{queryXmlFile}"</step>

			<!-- Explicitly require policy setup, gcam, and query steps to run after baseline in case we use baseline results in constraints -->
			<step name="setup" runFor="policy">@setup -b {baseline} -s {scenario} -g {scenarioGroup} -S {scenarioSubdir} -w {scenarioDir} -p {endYear} -y {years}</step>
			<step name="prequery" runFor="policy">@query -p -o {batchDir} -w {scenarioDir} -s {scenario} -q "{queryXmlFile}"</step>
			<step name="gcam"  runFor="policy">@gcam -s {scenario} -S {projectXmlDir}</step>
			<step name="query" runFor="policy">@query -o {batchDir} -w {scenarioDir} -s {scenario} -q "{queryXmlFile}"</step>

			<!-- Plot individual scenario results (differences are plotted in "plotDiff" step) -->
			<step name="plot"  runFor="all">@chart {scenPlotArgs} --scenario {scenario} --fromFile {scenPlots}</step>

			<!-- Compute and plot differences between query results for policy and baseline scenarios -->
			<step name="diff"     runFor="policy">@diff -D {sandboxDir} -y {years} -q {queryXmlFile} {baseline} {scenario}</step>
			<step name="plotDiff" runFor="policy">@chart {diffPlotArgs} --reference {baseline} --scenario {scenario} --fromFile {diffPlots}</step>

			<!-- Generate XLSX workbooks with standard and annually-interpolated results -->
			<step name="xlsx"     runFor="policy">@diff -D {diffsDir} -c -y {years} -o diffs.xlsx {diffsDir}/*.csv</step>
			<step name="xlsx"     runFor="policy">@diff -D {diffsDir} -c -y {years} -o "{scenario}-annual.xlsx" -i {diffsDir}/*.csv</step>
		</steps>

		<!-- Queries to run, including rewrites to perform on results -->
		<queries varName="queryXmlFile">
			<query name="aggregated_land_allocation">
				<rewriter name="eightRegions"/>
			</query>
			<query name="refined_liquids_production_by_tech">
				<rewriter name="liquidFuels"/>
			</query>
			<query name="total_climate_forcing"/>
      <query name="global_mean_temperature"/>
		</queries>

		<vars>
			<!-- common arguments to chart subcommand used for each line in the tmp file stored in variable 'scenPlots' -->
			<var name="scenPlotArgs" eval="1">-D {batchDir} --outputDir figures --years {years} --label --labelColor black --box</var>
		</vars>

		<tmpFile varName="scenPlots">
			<text>refined_liquids_production_by_tech-{scenario}.csv -Y EJ -I technology -i -T 'Refined liquid fuels production' -c region -n 4</text>
		</tmpFile>

		<vars>
			<!-- common arguments for 'diffPlots' -->
			<var name="diffPlotArgs" eval="1">-D {diffsDir} --outputDir figures --years {years} --label --ygrid --zeroLine</var>
		</vars>

		<tmpFile varName="diffPlots">
			<!-- Refined liquids production, USA alone, and global -->
			<text>refined_liquids_production_by_tech-{scenario}-{reference}.csv -c region -I technology -T '$\Delta$ Refined liquid fuels production (global)' -n 3</text>
			<text>refined_liquids_production_by_tech-{scenario}-{reference}.csv -x USA.png --region "USA" -c region -I technology -T '$\Delta$ Refined liquid fuels production (USA)' -n 3</text>

			<!-- Land allocation -->
			<text>aggregated_land_allocation-{scenario}-{reference}.csv -Y 'hectares' -m kkm2_to_ha -n 3 -x by-region-2050.png -c LandLeaf -I region -v 2050 --format=',' -T 'Area change (2050)'</text>

			<!-- Forcing and temperature change -->
			<text>total_climate_forcing-{scenario}-{reference}.csv   -Y 'W/m$^2$' --timeseries -T '$\Delta$ Total Climate Forcing'</text>
			<text>global_mean_temperature-{scenario}-{reference}.csv -Y 'Degrees C' --timeseries -T '$\Delta$ Global Mean Temperature'</text>
		</tmpFile>

	</project>
</projects>
