=== JGCRI/pygcam/pygcam/etc/protection-schema.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!-- Derived using MOSO Xmplify 1.7.6 by Richard Plevin on 2016-01-30 23:41:55 +0000 -->
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>
    <xs:element name='landProtection'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='group'/>
                <xs:element maxOccurs='unbounded' ref='scenario'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name='group'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='region'/>
            </xs:sequence>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='region' type='xs:string'/>
    <xs:element name='scenario'>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs='0' maxOccurs='unbounded' ref='protectedRegion'/>
            </xs:sequence>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='protectedRegion'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='protection'/>
            </xs:sequence>
            <xs:attribute name='name' use='required' type='xs:NCName'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='protection'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='landClass'/>
            </xs:sequence>
            <xs:attribute name='fraction' use='required' type='xs:decimal'/>
        </xs:complexType>
    </xs:element>
    <xs:element name='landClass' type='xs:NCName'/>
</xs:schema>

=== JGCRI/pygcam/tests/data/xml/protection.xml
<?xml version="1.0" encoding="UTF-8"?>
<landProtection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../pygcam/pygcam/etc/protection-schema.xsd">

    <group name="Developing">
        <region>Africa_Eastern</region>
        <region>Africa_Northern</region>
        <region>Africa_Southern</region>
        <region>Africa_Western</region>
        <region>Central America and Caribbean</region>
        <region>Central Asia</region>
        <region>Colombia</region>
        <region>Middle East</region>
        <region>Pakistan</region>
        <region>South America_Northern</region>
        <region>South America_Southern</region>
        <region>South Asia</region>
        <region>Southeast Asia</region>
    </group>

    <group name="MiddleIncome">
        <region>Brazil</region>
        <region>China</region>
        <region>India</region>
        <region>Indonesia</region>
        <region>Mexico</region>
        <region>South Africa</region>
    </group>

    <group name="Europe">
        <region>EU-12</region>
        <region>EU-15</region>
        <region>Europe_Eastern</region>
        <region>Europe_Non_EU</region>
        <region>European Free Trade Association</region>
    </group>

    <group name="Developed">
        <region>Argentina</region>
        <region>Australia_NZ</region>
        <region>Canada</region>
        <region>Europe</region>     <!-- group names (e.g., Europe) are expanded to the underlying regions -->
        <region>Japan</region>
        <region>Russia</region>
        <region>South Korea</region>
        <region>Taiwan</region>
        <region>USA</region>
    </group>

    <scenario name="test">
        <!--
        Scenarios define a level of land protection for regions or groups.
        Regions are processed in the order defined. Any redefinition of the
        protection in a region overwrites what was given previously. This
        allows the use of groups followed by differentiation for individual
        regions within the group.
        -->
        <protectedRegion name="Developing">
            <protection>
                <fraction>0.5</fraction>
                <landClass>UnmanagedForest</landClass>
                <landClass>UnmanagedPasture</landClass>
            </protection>
            <protection>
                <fraction>0.25</fraction>
                <landClass>Shrubland</landClass>
                <landClass>Grassland</landClass>
            </protection>
        </protectedRegion>

        <protectedRegion name="MiddleIncome">
            <protection>
                <fraction>0.7</fraction>
                <landClass>UnmanagedForest</landClass>
                <landClass>UnmanagedPasture</landClass>
            </protection>
            <protection>
                <fraction>0.4</fraction>
                <landClass>Shrubland</landClass>
                <landClass>Grassland</landClass>
            </protection>
        </protectedRegion>

        <!-- This overrides Brazil's definition in MiddleIncome -->
        <protectedRegion name="Brazil">
            <protection>
                <fraction>0.5</fraction>
                <landClass>UnmanagedForest</landClass>
            </protection>
            <protection>
                <fraction>0.4</fraction>
                <landClass>UnmanagedPasture</landClass>
                <landClass>Shrubland</landClass>
                <landClass>Grassland</landClass>
            </protection>
        </protectedRegion>

        <protectedRegion name="Developed">
            <protection>
                <fraction>0.9</fraction>
                <landClass>UnmanagedForest</landClass>
                <landClass>UnmanagedPasture</landClass>
            </protection>
            <protection>
                <fraction>0.5</fraction>
                <landClass>Shrubland</landClass>
                <landClass>Grassland</landClass>
            </protection>
        </protectedRegion>
    </scenario>
</landProtection>
