=== JGCRI/pygcam/pygcam/etc/rewriteSets-schema.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

    <xs:element name='rewriteSets'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element ref='rewriteSet'/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:element name='rewriteSet'>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs='unbounded' ref='rewrite'/>
            </xs:sequence>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='level' use='required' type='xs:string'/>
            <xs:attribute name='byAEZ' type='xs:string'/>
            <xs:attribute name='append-values' type='xs:boolean'/>
        </xs:complexType>
    </xs:element>

    <xs:element name='rewrite'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='to' use='required' type='xs:string'/>
                    <xs:attribute name='from' use='required' type='xs:string'/>
                    <xs:attribute name='byAEZ' type='xs:string'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JGCRI/pygcam/pygcam/etc/examples/rewriteSets.xml
<?xml version="1.0"?>
<rewriteSets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:noNamespaceSchemaLocation="rewriteSets-schema.xsd">

	<rewriteSet name="liquidFuels" level="technology" append-values="false">
		<rewrite from="cellulosic ethanol" to="Cellulosic ethanol"/>
		<rewrite from="corn ethanol" to="Corn ethanol"/>
		<rewrite from="sugar cane ethanol" to="Sugar cane ethanol"/>
		<rewrite from="cellulosic ethanol CCS level 1" to="Cellulosic ethanol"/>
		<rewrite from="cellulosic ethanol CCS level 2" to="Cellulosic ethanol"/>
		<rewrite from="FT biofuels" to="FT biofuels"/>
		<rewrite from="biodiesel" to="Oilcrop biodiesel"/>
		<rewrite from="FT biofuels CCS level 1" to="FT biofuels"/>
		<rewrite from="FT biofuels CCS level 2" to="FT biofuels"/>
		<rewrite from="coal to liquids" to="CTL"/>
		<rewrite from="coal to liquids CCS level 1" to="CTL"/>
		<rewrite from="coal to liquids CCS level 2" to="CTL"/>
		<rewrite from="crude oil refining" to="Oil refining"/>
		<rewrite from="oil refining" to="Oil refining"/>
		<rewrite from="gas to liquids" to="GTL"/>
		<rewrite from="unconventional oil refining" to="Oil refining"/>
	</rewriteSet>

	<rewriteSet name="eightRegions" level="region" append-values="true">
		<rewrite from="USA" to="United States"/>
		<rewrite from="Brazil" to="Brazil"/>
		<rewrite from="Canada" to="Rest of World"/>
		<rewrite from="China" to="China"/>
		<rewrite from="Africa_Eastern" to="Africa"/>
		<rewrite from="Africa_Northern" to="Africa"/>
		<rewrite from="Africa_Southern" to="Africa"/>
		<rewrite from="Africa_Western" to="Africa"/>
		<rewrite from="Japan" to="Rest of Asia"/>
		<rewrite from="South Korea" to="Rest of Asia"/>
		<rewrite from="India" to="Rest of Asia"/>
		<rewrite from="Central America and Caribbean" to="Rest of South America"/>
		<rewrite from="Central Asia" to="Rest of Asia"/>
		<rewrite from="EU-12" to="Europe Union 27"/>
		<rewrite from="EU-15" to="Europe Union 27"/>
		<rewrite from="Europe_Eastern" to="Rest of World"/>
		<rewrite from="Europe_Non_EU" to="Rest of World"/>
		<rewrite from="European Free Trade Association" to="Rest of World"/>
		<rewrite from="Indonesia" to="Rest of Asia"/>
		<rewrite from="Mexico" to="Rest of South America"/>
		<rewrite from="Middle East" to="Rest of World"/>
		<rewrite from="Pakistan" to="Rest of Asia"/>
		<rewrite from="Russia" to="Rest of World"/>
		<rewrite from="South Africa" to="Africa"/>
		<rewrite from="South America_Northern" to="Rest of South America"/>
		<rewrite from="South America_Southern" to="Rest of South America"/>
		<rewrite from="South Asia" to="Rest of Asia"/>
		<rewrite from="Southeast Asia" to="Rest of Asia"/>
		<rewrite from="Taiwan" to="Rest of Asia"/>
		<rewrite from="Argentina" to="Rest of South America"/>
		<rewrite from="Colombia" to="Rest of South America"/>
		<rewrite from="Australia_NZ" to="Rest of Asia"/>
	</rewriteSet>

	<rewriteSet name="food" level="input">
		<rewrite from="Corn" to="Grains"/>
		<rewrite from="FiberCrop" to="Other"/>
		<rewrite from="MiscCrop" to="Other"/>
		<rewrite from="OilCrop" to="Other"/>
		<rewrite from="OtherGrain" to="Grains"/>
		<rewrite from="PalmFruit" to="Other"/>
		<rewrite from="Rice" to="Grains"/>
		<rewrite from="Root_Tuber" to="Other"/>
		<rewrite from="SugarCrop" to="Other"/>
		<rewrite from="Wheat" to="Grains"/>
		<rewrite from="regional beef" to="Meat"/>
		<rewrite from="Dairy" to="Meat"/>
		<rewrite from="OtherMeat_Fish" to="Meat"/>
		<rewrite from="Pork" to="Meat"/>
		<rewrite from="Poultry" to="Meat"/>
		<rewrite from="SheepGoat" to="Meat"/>
	</rewriteSet>

	<rewriteSet name="landCover" level="LandLeaf" byAEZ="true">
		<rewrite from="biomass" to="Biomass"/>
		<rewrite from="Corn" to="Cropland"/>
		<rewrite from="eucalyptus" to="Cropland"/>
		<rewrite from="FiberCrop" to="Cropland"/>
		<rewrite from="FodderGrass" to="Cropland"/>
		<rewrite from="FodderHerb" to="Cropland"/>
		<rewrite from="Forest" to="Forest (managed)"/>
		<rewrite from="Grassland" to="Grass"/>
		<rewrite from="Jatropha" to="Cropland"/>
		<rewrite from="miscanthus" to="Biomass"/>
		<rewrite from="MiscCrop" to="Cropland"/>
		<rewrite from="OilCrop" to="Cropland"/>
		<rewrite from="OtherArableLand" to="Cropland"/>
		<rewrite from="OtherGrain" to="Cropland"/>
		<rewrite from="PalmFruit" to="Cropland"/>
		<rewrite from="Pasture" to="Pasture (grazed)"/>
		<rewrite from="ProtectedGrassland" to="Other arable land"/>
		<rewrite from="ProtectedShrubland" to="Other arable land"/>
		<rewrite from="ProtectedUnmanagedForest" to="Forest (unmanaged)"/>
		<rewrite from="ProtectedUnmanagedPasture" to="Pasture (other)"/>
		<rewrite from="Rice" to="Cropland"/>
		<rewrite from="RockIceDesert" to="Other land"/>
		<rewrite from="Root_Tuber" to="Cropland"/>
		<rewrite from="Shrubland" to="Other arable land"/>
		<rewrite from="SugarCrop" to="Cropland"/>
		<rewrite from="Tundra" to="Other land"/>
		<rewrite from="UnmanagedForest" to="Forest (unmanaged)"/>
		<rewrite from="UnmanagedPasture" to="Pasture (other)"/>
		<rewrite from="UrbanLand" to="Other land"/>
		<rewrite from="Wheat" to="Cropland"/>
		<rewrite from="willow" to="Cropland"/>
		<rewrite from="SugarcaneEthanol" to="Cropland"/>
	</rewriteSet>
</rewriteSets>
