=== JGCRI/pygcam/pygcam/etc/scenarios-schema.xsd
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='qualified'>

	<xs:include schemaLocation="conditional.xsd"/>
    <xs:include schemaLocation="comment.xsd"/>

	<xs:simpleType name="iteratorType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="float"/>
			<xs:enumeration value="int"/>
            <xs:enumeration value="list"/>
        </xs:restriction>
    </xs:simpleType>

	<xs:simpleType name="comparison">
		<xs:restriction base="xs:string">
			<xs:enumeration value="is"/>
			<xs:enumeration value="isNot"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name='scenarios'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs="0" ref='iterator'/>
                <xs:element ref='scenarioGroup'/>
                <xs:element ref='comment'/>
                <xs:element ref='CONDITIONAL'/>
            </xs:choice>
            <xs:attribute name='name' type='xs:string'/>            <!-- TBD: unused currently -->
            <xs:attribute name='defaultGroup' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:element name='iterator'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='name' use='required' type='xs:string'/>
                    <xs:attribute name='type' type='iteratorType' default="list"/>
                    <xs:attribute name='min' type='xs:decimal'/>
                    <xs:attribute name='max' type='xs:decimal'/>
                    <xs:attribute name='step' type='xs:decimal'/>
                    <xs:attribute name='format' type='xs:string'/>
                    <xs:attribute name='values' type='xs:string'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name='scenarioGroup'>
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref='scenario'/>
                <xs:element ref='comment'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='useGroupDir' type='xs:boolean' default='false'/>
            <xs:attribute name='srcGroupDir' type='xs:string'/>
            <xs:attribute name='iterator' type='xs:string'/>
            <xs:attribute name='baselineSource' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:element name='scenario'>
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs="0" ref='insert'/>
                <xs:element minOccurs="0" ref='add'/>
                <xs:element minOccurs="0" ref='replace'/>
                <xs:element minOccurs="0" ref='delete'/>
                <xs:element minOccurs="0" ref='function'/>
                <xs:element minOccurs="0" ref='if'/>
                <xs:element minOccurs="0" ref='CONDITIONAL'/>
                <xs:element minOccurs="0" ref='comment'/>
            </xs:choice>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='active' type='xs:boolean' default='true'/>      <!-- TBD: drop this? -->
            <xs:attribute name='baseline' type='xs:boolean'/>
            <xs:attribute name='iterator' type='xs:string'/>
            <xs:attribute name='subdir' type='xs:string'/>                      <!-- TBD-->

        </xs:complexType>
    </xs:element>

    <!-- <function name="protectLand">{fraction}, unprotectFirst=True, otherArable=False</function> -->
    <xs:element name='function'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='name' use='required' type='xs:string'/>
                    <xs:attribute name='dynamic' type='xs:boolean'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name='insert'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='name' use='required' type='xs:string'/>
                    <xs:attribute name='dir' type='xs:string'/>
                    <xs:attribute name='after' use='required' type='xs:string'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name='add'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='name' use='required' type='xs:string'/>
                    <xs:attribute name='dir' type='xs:string'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name='replace'>
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name='name' use='required' type='xs:string'/>
                    <xs:attribute name='dir' type='xs:string'/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name='delete'>
        <xs:complexType>
            <xs:attribute name='name' use='required' type='xs:string'/>
            <xs:attribute name='dir' type='xs:string'/>
        </xs:complexType>
    </xs:element>

    <xs:element name="if">
        <xs:complexType>
            <xs:choice maxOccurs='unbounded'>
                <xs:element minOccurs="0" ref='insert'/>
                <xs:element minOccurs="0" ref='add'/>
                <xs:element minOccurs="0" ref='replace'/>
                <xs:element minOccurs="0" ref='delete'/>
                <xs:element minOccurs="0" ref='function'/>
                <xs:element minOccurs="0" ref='if'/>
                <xs:element minOccurs="0" ref='CONDITIONAL'/>
                <xs:element minOccurs="0" ref='comment'/>
            </xs:choice>
            <xs:attribute name='value1'  type='xs:string' use='required' />
            <xs:attribute name='value2'  type='xs:string' use='required' />
            <xs:attribute name='matches' type='xs:boolean' default="1"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JGCRI/pygcam/pygcam/etc/examples/tutorial-scenarios.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Example of XML setup for "simple" tutorial project -->

<scenarios name="uniqueName" defaultGroup="group"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="scenarios-schema.xsd">

    <scenarioGroup name="group" useGroupDir="0">
        <scenario name="base" baseline="1">
            <!-- unmodified GCAM reference scenario -->
        </scenario>

        <scenario name="tax-10">
            <add name="carbon_tax">../input/policy/carbon_tax_10_5.xml</add>
        </scenario>

        <scenario name="tax-25">
            <add name="carbon_tax">../input/policy/carbon_tax_25_5.xml</add>
        </scenario>

        <scenario name="tax-bio-10">
            <add name="carbon_tax">../input/policy/carbon_tax_10_5.xml</add>
            <function name="taxBioCarbon"/>
        </scenario>

        <scenario name="tax-bio-25">
            <add name="carbon_tax">../input/policy/carbon_tax_25_5.xml</add>
            <function name="taxBioCarbon"/>
        </scenario>
    </scenarioGroup>
</scenarios>

=== JGCRI/pygcam/pygcam/etc/examples/scenarios-iterator.xml
<scenarios name="uniqueName" defaultGroup="group"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="scenarios-schema.xsd">

      <!-- Our policy scenarios will use these levels of carbon taxes -->
    <iterator name="tax"   type="list" values="10,15,20,25"/>

    <scenarioGroup name="group" useGroupDir="0">
        <scenario name="base" baseline="1">
            <!-- unmodified GCAM reference scenario -->
        </scenario>

        <scenario name="tax-{tax}" iterator="tax">
            <!-- Add a line to the XML config file to load this file -->
            <add name="carbon_tax">../input/policy/carbon_tax_{tax}_5.xml</add>
        </scenario>

        <!-- As above, but also tax biogenic CO2 -->
        <scenario name="tax-bio-{tax}" iterator="tax">
            <add name="carbon_tax">../input/policy/carbon_tax_{tax}_5.xml</add>
            <function name="taxBioCarbon"/>
        </scenario>
    </scenarioGroup>
</scenarios>
